//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace termProjectMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string specification { get; set; }
        public string price { get; set; }
        public Nullable<int> cid_ { get; set; }
        public Nullable<int> bid { get; set; }
        public string imageName { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> uid1 { get; set; }
    
        public virtual brand brand { get; set; }
        public virtual category category { get; set; }
        public virtual user user { get; set; }
        public virtual user1 user1 { get; set; }
    }
}
